"""make short_code nullable

Revision ID: b3393bd18a59
Revises: e70f66ee5fe2
Create Date: 2026-08-22 21:54:00.204661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3393bd18a59'
down_revision: Union[str, Sequence[str], None] = 'e70f66ee5fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_mapper', 'short_code',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.drop_constraint(op.f('url_mapper_short_code_key'), 'url_mapper', type_='unique')
    op.create_index(op.f('ix_url_mapper_short_code'), 'url_mapper', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_mapper_short_code'), table_name='url_mapper')
    op.create_unique_constraint(op.f('url_mapper_short_code_key'), 'url_mapper', ['short_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('url_mapper', 'short_code',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###
