"""create url_mapper table

Revision ID: f6590a8bb1ad
Revises: 
Create Date: 2026-08-09 12:44:15.447491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6590a8bb1ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=4), nullable=False),
    sa.Column('long_url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_mapper')
    # ### end Alembic commands ###
